name: Deploy

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - main

permissions:
  contents: write
  pull-requests: write


jobs:
  cdk_deploy:
    runs-on: ubuntu-latest

    # # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
    # concurrency: ${{ github.ref_name }}

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    # see https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
    permissions:
      id-token: write
      contents: read

    environment:
      name: ${{ github.ref_name }}

    env:
      AWS_CDK_STACKS: null
      AWS_CDK_STACKS_IGNORE_DEPENDENCY: false
      AWS_CDK_STACKS_EXPRESSION: --all
      AWS_OIDC_ROLE_ARN: test-role-arn
      AWS_REGION: test-region
      ENVIRONMENT_MODE: test-mode
      ENVIRONMENT_ID: test-id
      NODE_VERSION: '18.17.1'
      PNPM_VERSION: '8.6.12'

    steps:
      - name: Check out
        uses: actions/checkout@v4
        # with:
        #   submodules: 'recursive'
          # TODO: Separate the account used for checking out the submodules
          # once we have a less privileged account
          # ssh-key: ${{ secrets.SUBMODULE_SYNC_SSH_KEY }}
      
      - name: CDK Deploy
        # working-directory: ./aaaaaaa
        # run: npx cdk deploy --require-approval never --context environmentMode=${{env.ENVIRONMENT_MODE}} --context environmentId=${{ env.ENVIRONMENT_ID }}
        run: cd aaaaaaa && npx --yes cdk --version
