name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Manually set commitizen increment'
        required: false
        default: auto
        type: choice
        options:
          - auto
          - PATCH
          - MINOR
          - MAJOR

permissions:
  contents: write
  pull-requests: write


jobs:
  bump_version:
    name: "Bump version and create changelog with commitizen"
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Commitizen stuff
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.16.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md
          push: false
          extra_requirements: typing-extensions
          increment: ${{ (github.event.inputs.increment != 'auto' && github.event.inputs.increment) || '' }}

      - id: czmessage
        name: Save cz changelog
        run: |
          export BODY=$(cat body.md)
          BODY="${BODY//'%'/'%25'}"
          BODY="${BODY//$'\n'/'%0A'}"
          BODY="${BODY//$'\r'/'%0D'}"
          echo "::set-output name=body::$BODY"
          echo "::set-output name=last_commit_message::$(git log -1 --pretty=format:"%s")"
          rm body.md

      - name: Move tag
        run: |
          git tag -f ${{ steps.cz.outputs.version }} HEAD^1

      # Create PR for the bump
      - name: Create PR
        uses: peter-evans/create-pull-request@v4.0.2
        with:
          title: ${{ steps.czmessage.outputs.last_commit_message }}
          body: ${{ steps.czmessage.outputs.body }}
          branch: "release/${{ steps.cz.outputs.version }}"
          draft: false
          maintainer_can_modify: true
          delete-branch: true

      - name: Push the tag
        run: git push origin ${{ steps.cz.outputs.version }}